/**
 * MDES for Merchants
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed.  All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded.  Each API URI includes the major and minor version of API that it conforms to.  This will allow multiple concurrent versions of the API to be deployed simultaneously.  
 *
 * The version of the OpenAPI document: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TransactError from '../model/TransactError';
import TransactRequestSchema from '../model/TransactRequestSchema';
import TransactResponseSchema from '../model/TransactResponseSchema';

/**
* Transact service.
* @module api/TransactApi
* @version 1.2.7
*/
export default class TransactApi {

    /**
    * Constructs a new TransactApi. 
    * @alias module:api/TransactApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTransact operation.
     * @callback module:api/TransactApi~createTransactCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TransactResponseSchema} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Used by the Token Requestor to create a Digital Secure Remote Payment (\"DSRP\") transaction cryptogram using the credentials stored within MDES in order to perform a DSRP transaction.
     * This API is used by the Token Requestor to create a Digital Secure Remote Payment (\"DSRP\") transaction cryptogram using the credentials stored within MDES in order to perform a DSRP transaction through a payment processor.  The entire response is encrypted. The caller may only transact using the Tokens belonging to them. 
     * @param {Object} opts Optional parameters
     * @param {module:model/TransactRequestSchema} opts.transactRequestSchema Contains the details of the request message. 
     * @param {module:api/TransactApi~createTransactCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TransactResponseSchema}
     */
    createTransact(opts, callback) {
      opts = opts || {};
      let postBody = opts['transactRequestSchema'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TransactResponseSchema;
      return this.apiClient.callApi(
        '/remotetransaction/static/1/0/transact', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
