/**
 * MDES for Merchants
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed.  All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded.  Each API URI includes the major and minor version of API that it conforms to.  This will allow multiple concurrent versions of the API to be deployed simultaneously.  
 *
 * The version of the OpenAPI document: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetTaskStatusRequestSchema model module.
 * @module model/GetTaskStatusRequestSchema
 * @version 1.2.7
 */
class GetTaskStatusRequestSchema {
    /**
     * Constructs a new <code>GetTaskStatusRequestSchema</code>.
     * @alias module:model/GetTaskStatusRequestSchema
     * @param requestId {String} Unique identifier for the request. 
     * @param taskId {String} Unique identifier for this task. Must be an identifier previously used when requesting a task.    __Max Length:64__ 
     */
    constructor(requestId, taskId) { 
        
        GetTaskStatusRequestSchema.initialize(this, requestId, taskId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestId, taskId) { 
        obj['requestId'] = requestId;
        obj['taskId'] = taskId;
    }

    /**
     * Constructs a <code>GetTaskStatusRequestSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTaskStatusRequestSchema} obj Optional instance to populate.
     * @return {module:model/GetTaskStatusRequestSchema} The populated <code>GetTaskStatusRequestSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTaskStatusRequestSchema();

            if (data.hasOwnProperty('responseHost')) {
                obj['responseHost'] = ApiClient.convertToType(data['responseHost'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('tokenRequestorId')) {
                obj['tokenRequestorId'] = ApiClient.convertToType(data['tokenRequestorId'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The host that originated the request. Future calls in the same conversation may be routed to this host. 
 * @member {String} responseHost
 */
GetTaskStatusRequestSchema.prototype['responseHost'] = undefined;

/**
 * Unique identifier for the request. 
 * @member {String} requestId
 */
GetTaskStatusRequestSchema.prototype['requestId'] = undefined;

/**
 * Identifies the Token Requestor.  __Length:11__ 
 * @member {String} tokenRequestorId
 */
GetTaskStatusRequestSchema.prototype['tokenRequestorId'] = undefined;

/**
 * Unique identifier for this task. Must be an identifier previously used when requesting a task.    __Max Length:64__ 
 * @member {String} taskId
 */
GetTaskStatusRequestSchema.prototype['taskId'] = undefined;






export default GetTaskStatusRequestSchema;

