/**
 * MDES for Merchants
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed.  All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded.  Each API URI includes the major and minor version of API that it conforms to.  This will allow multiple concurrent versions of the API to be deployed simultaneously.  
 *
 * The version of the OpenAPI document: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardInfo from './CardInfo';

/**
 * The SearchTokensRequestSchema model module.
 * @module model/SearchTokensRequestSchema
 * @version 1.2.7
 */
class SearchTokensRequestSchema {
    /**
     * Constructs a new <code>SearchTokensRequestSchema</code>.
     * @alias module:model/SearchTokensRequestSchema
     * @param requestId {String} Unique identifier for the request. 
     */
    constructor(requestId) { 
        
        SearchTokensRequestSchema.initialize(this, requestId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestId) { 
        obj['requestId'] = requestId;
    }

    /**
     * Constructs a <code>SearchTokensRequestSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchTokensRequestSchema} obj Optional instance to populate.
     * @return {module:model/SearchTokensRequestSchema} The populated <code>SearchTokensRequestSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchTokensRequestSchema();

            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('responseHost')) {
                obj['responseHost'] = ApiClient.convertToType(data['responseHost'], 'String');
            }
            if (data.hasOwnProperty('cardInfo')) {
                obj['cardInfo'] = CardInfo.constructFromObject(data['cardInfo']);
            }
            if (data.hasOwnProperty('tokenRequestorId')) {
                obj['tokenRequestorId'] = ApiClient.convertToType(data['tokenRequestorId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique identifier for the request. 
 * @member {String} requestId
 */
SearchTokensRequestSchema.prototype['requestId'] = undefined;

/**
 * The host that originated the request. Future calls in the same conversation may be routed to this host. 
 * @member {String} responseHost
 */
SearchTokensRequestSchema.prototype['responseHost'] = undefined;

/**
 * @member {module:model/CardInfo} cardInfo
 */
SearchTokensRequestSchema.prototype['cardInfo'] = undefined;

/**
 * Identifies the Token Requestor. Only tokens associated with the token requestor will be returned. Length - 11.  
 * @member {String} tokenRequestorId
 */
SearchTokensRequestSchema.prototype['tokenRequestorId'] = undefined;






export default SearchTokensRequestSchema;

