/**
 * MDES for Merchants
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed.  All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded.  Each API URI includes the major and minor version of API that it conforms to.  This will allow multiple concurrent versions of the API to be deployed simultaneously.  
 *
 * The version of the OpenAPI document: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BillingAddress model module.
 * @module model/BillingAddress
 * @version 1.2.7
 */
class BillingAddress {
    /**
     * Constructs a new <code>BillingAddress</code>.
     * @alias module:model/BillingAddress
     */
    constructor() { 
        
        BillingAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BillingAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingAddress} obj Optional instance to populate.
     * @return {module:model/BillingAddress} The populated <code>BillingAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingAddress();

            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
            if (data.hasOwnProperty('line2')) {
                obj['line2'] = ApiClient.convertToType(data['line2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('countrySubdivision')) {
                obj['countrySubdivision'] = ApiClient.convertToType(data['countrySubdivision'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * __(OPTIONAL)__<br> The first line of the street address for the billing address.<br> __Max Length:64__ 
 * @member {String} line1
 */
BillingAddress.prototype['line1'] = undefined;

/**
 * __(OPTIONAL)__ The second line of the street address for the billing address.<br> __Max Length:64__ 
 * @member {String} line2
 */
BillingAddress.prototype['line2'] = undefined;

/**
 * __(OPTIONAL)__<br> The city of the billing address.<br> __Max Length:32__ 
 * @member {String} city
 */
BillingAddress.prototype['city'] = undefined;

/**
 * __(OPTIONAL)__<br> The state or country subdivision of the billing address.<br> __Max Length:12__ 
 * @member {String} countrySubdivision
 */
BillingAddress.prototype['countrySubdivision'] = undefined;

/**
 * __(OPTIONAL)__<br> The postal of code of the billing address.<br> __Max Length:16__ 
 * @member {String} postalCode
 */
BillingAddress.prototype['postalCode'] = undefined;

/**
 * __(OPTIONAL)__ The country of the billing address. <br> __Max Length:3__ 
 * @member {String} country
 */
BillingAddress.prototype['country'] = undefined;






export default BillingAddress;

