"source": {
    "type": "card",
    "number": "4541249167673670",
    "cvv": "120",
    "expiry_month": 12,
    "expiry_year": 2030
  },
  "currency": "USD",
  "amount": 1500,
  "processing_channel_id": "pc_dkgoofpvuwuerekvd4ssr6jwom"
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v ./README.md ./csharp/README.md ./java/README.md ./nodejs/README.md ./php/README.md ./python/README.md ./ruby/README.md -x (GIT_REPO_ID|api.mastercard.com)
      - name: Fail?
        run: exit ${{ steps.lc.outputs.exit_code }}
